### ISSUE TITLE
Retry to connect even after fatal connection errors

### ISSUE THREAD

**Issue by alshakero** [Palindrom/palindrom-polymer-client#53]
When I was in Stockholm, @andwah pointed out that `palindrom-polymer-client` needs to reconnect even after fatal errors. This is especially needed for apps that stay idle for a long time by design. 

Imagine a clock app, it shouldn't die when you restart the server, which is considered a fatal error.

**Comment by alshakero** [comment]
PR in https://github.com/Palindrom/palindrom-polymer-client/pull/56

**Comment by warpech** [comment]
Automatic reloading after 5 seconds from an exception means that it will be harder for app developers to detect uncaught exceptions in their view-models. Palindrom will reload the page, obscuring the real problem.

That might not be a problem in the end, because:

1. reloading can be dismissed by clicking "Cancel reloading" (if you manage to click on that within 5 seconds)
2. the information about the uncaught exception can still be found in the Administrator log.

@Mihaiii, @mmnosek, @LarsTjernstrom, @habib535, @bouguila, @Joltrix is that OK for you?

If this is a problem, we can explore overriding this setting through [configuring the middleware](https://github.com/Starcounter/RebelsLounge/issues/146) or handling the error event in Starcounter DevTools browser extension.

**Comment by Mihaiii** [comment]
It's ok with me, but please ping me when you make the PR in level1 so I can test Admin (something similar was requested and implemented on the `onConnectionError`) and make changes in Admin app, if needed.

**Comment by alshakero** [comment]
> Automatic reloading after 5 seconds from an exception means that it will be harder for app developers to detect uncaught exceptions in their view-models. Palindrom will reload the page, obscuring the real problem.

I can also disable reloading when Chrome DevTools is open.

**Comment by warpech** [comment]
> I can also disable reloading when Chrome DevTools is open.

I like that. Can the same be done for Firefox, Safari, Edge DevTools and Starcounter DevTools?

**Comment by alshakero** [comment]
Yes it can.

**Comment by andwah** [comment]
Wonder if there is a (cool) way of telling the client that the server has been stopped manually (by admin), if so then we can have some nice message telling that the server has been stopped and auto retry to connect each 5sec or so.. otherwize show the error?

**Comment by warpech** [comment]
WebSocket has a way to send a closing message so that is absolutely possible, but it is beyond this issue.

Care to make an issue for that in level1?

**Comment by alshakero** [comment]
FF 
![image](https://user-images.githubusercontent.com/17054134/35286978-ab97605c-0061-11e8-9eb0-30ca8ea3271e.png)

Chrome
![image](https://user-images.githubusercontent.com/17054134/35287010-baeaa29e-0061-11e8-8ba6-9495f4fc1ea6.png)
